name: Test & Deploy
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build the code
        run: npm run build
      - name: Commit & push to gh-pages branch
        run: |
          git checkout -b gh-pages
          git add .
          git commit -m "Auto commit for deployment"
          git push origin/gh-pages
